import os
import json

COMMON_PATH = os.getenv('COMMON_PATH')
concepts = {}
# Should decide if it's outdoor or indoor
# keyword: [must] [should] [except]
def add_itself(deeplab_kw, properties):
    if len(properties) == 4:
        remove = properties[3]
    else:
        remove = []
    try:
        properties[1].extend([w for w in deeplab_kw.split(';') if w not in remove])
    except Exception as e:
        print(e)
        print(deeplab_kw)
    if len(properties) == 2:
        properties.append([])
    return properties[:3]

# Add the keywords to themselves
map2deeplab = {"airplane;aeroplane;plane": ["outdoor", []],
               "animal;animate;being;beast;brute;creature;fauna": ["", ["bird", "dog", "cat", "horse",
                                                                        "sheep", "cow", "elephant", "bear",
                                                                        "zebra", "giraffe"], [],
                                                                   ["being", "animate"]],
               "apparel;wearing;apparel;dress;clothes": ["indoor", ["cloth", "tie"]],
               "arcade;machine": ["indoor", ["arcade machine"], [], ["machine"]],
               "armchair": ["indoor", ["couch", "sofa", "lounge", "seat"]],
               "ashcan;trash;can;garbage;can;wastebin;ash;bin;ash-bin;ashbin;dustbin;trash;barrel;trash;bin":
                   ["indoor",
                    ["garbage can"],
                    [], ["can", "ash", "barrel"]],
               "awning;sunshade;sunblind": ["outdoor", []],
               "bag": ["", ["backpack", "handbag", "purse", "suitcase"]],
               "ball": ["", ["sports ball", "soccer ball"]],
               "bannister;banister;balustrade;balusters;handrail": ["",
                                                                    ["bridge", "airbridge", "staircase", "balcony",
                                                                     "escalator", "staircase"]],
               "bar": ["indoor", ["counter"]],
               "barrel;cask": ["indoor", []],
               "base;pedestal;stand": ["", ["stand", "store", "shop", "supermarket", "display"], [],
                                       ["base", "pedestal"]], "basket;handbasket": ["", []],
               "bathtub;bathing;tub;bath;tub": ["indoor", ["bathroom", "faucet", "tap"]],
               "bed": ["indoor", ["blanket"]],
               "bench": ["", ["seat", "chair", "lounge"]],
               "bicycle;bike;wheel;cycle": ["", [], [], ["wheel", "cycle"]],
               "blanket;cover": ["", ["bed", "bed cover"], [], ["cover"]],
               "blind;screen": ["indoor", ["curtain", "blinder", "cloak", "window cover", "veil",
                                           "drape", "drapery", "mantle", "pall"], [], ["screen"]],
               "boat": ["outdoor", ["ship", "harbor"]],
               "book": ["", []],
               "bookcase": ["indoor", ["bookshelf", "book shelf", "book case", "archive"]],
               "booth;cubicle;stall;kiosk": ["", ["stand", "newsstand"]],
               "bottle": ["", []],
               "box": ["indoor", []],
               "bridge;span": ["outdoor", [], [], ["span"]],
               "buffet;counter;sideboard": ["indoor", ["buffet counter"], [], ["counter"]],
               "building;edifice": ["outdoor", ["house", "building", "church", "house", "roof", "hut"],
                                    ["shop", "store", "hotel"]],
               "bulletin;board;notice;board": ["indoor", ["bulletin board", "sign board",
                                                          "advertisement", "sign", "notice board",
                                                          "poster", "placard", "billboard", "poster"]],
               "bus;autobus;coach;charabanc;double-decker;jitney;motorbus;motorcoach;omnibus;passenger;vehicle": ["",
                                                                                                                  [],
                                                                                                                  [],
                                                                                                                  [
                                                                                                                      "passenger",
                                                                                                                      "vehical"]],
               "cabinet": ["indoor", ["case", "closet", "container", "dresser", "locker"], ["kitchen"]],
               "canopy": ["", []],
               "car;auto;automobile;machine;motorcar": ["", [], [], ["machine"]],
               "case;display;case;showcase;vitrine": ["", ["shelf"]],
               "ceiling": ["indoor", []],
               "chair": ["indoor", ["conference center", "auditorium", "lounge", "stool"]],
               "chandelier;pendant;pendent": ["indoor", ["lamp", "candle", "bulb", "light"]],
               "chest;of;drawers;chest;bureau;dresser": ["indoor", ["drawer"], [], ["of", "drawers"]],
               "clock": ["indoor", []],
               "coffee;table;cocktail;table": ["indoor", ["coffee table", "cocktail table"], [],
                                               ["coffee", "cocktail"]],
               "column;pillar": ["", ["pole"]],
               "computer;computing;machine;computing;device;data;processor;electronic;computer;information;processing;system": [
                   "indoor", ["pc", "personal computer", "monitor", "mouse", "speaker"], [],
                   ["machine", "device", "data", "processor", "electronic", "information", "processing"]],
               "conveyer;belt;conveyor;belt;conveyer;conveyor;transporter": ["indoor",
                                                                             ["conveyer belt", "baggage claim"],
                                                                             [], ["belt", "transporter"]],
               "counter": ["indoor", ["reception", "counter", "kitchen island"]],
               "countertop": ["indoor", ["counter", "reception", "bathroom"]],
               "cradle": ["indoor", []],
               "crt;screen": ["indoor", ["tv", "television", "monitor"]],
               "curtain;drape;drapery;mantle;pall": ["indoor",
                                                     ["curtain", "blinder", "cloak", "window cover", "veil", "blind"]],
               "cushion": ["indoor", ["pillow"]],
               "desk": ["indoor", ["table"]],
               "dirt;track": ["outdoor", ["dirt track", "field road", "dirt road", "path"]],
               "dishwasher;dish;washer;dishwashing;machine": ["indoor", ["dish washer", "dishwashing machine"],
                                                              [], ["machine"]],
               "door;double;door": ["", ["double door"], [], ["double"]],
               "earth;ground": ["outdoor", [], ["grass", "field", "garden", "lawn", "mountain"]],
               "escalator;moving;staircase;moving;stairway": ["indoor", ["stairs", "steps"], [], ["moving"]],
               "fan": ["indoor", []],
               "fence;fencing": ["outdoor", ["railing", "rail", "bannister", "banister", "balustrade",
                                             "balusters", "handrail", "balcony"]],
               "field": ["outdoor", []],
               "fireplace;hearth;open;fireplace": ["indoor", [], [], ["open"]],
               "flag": ["", [], []],
               "floor;flooring": ["indoor", []],
               "flower": ["", []],
               "food;solid;food": ["indoor", ["banana", "apple", "sandwich", "orange", "broccoli",
                                              "carrot", "hot dog", "pizza", "donut",
                                              "cake"], [], ["solid"]],
               "fountain": ["", []],
               "glass;drinking;glass": ["indoor", ["drinking glass", "wine glass"]],
               "grandstand;covered;stand": ["", [], [], ["covered"]],
               "grass": ["outdoor", [], ["field"]],
               "hill": ["outdoor", ["valley", "mountain"]],
               "hood;exhaust;hood": ["indoor", ["kitchen", "exhaust hood"]],
               "house": ["outdoor", ["building"]],
               "hovel;hut;hutch;shack;shanty": ["outdoor", ["cabin", "house"]],
               "kitchen;island": ["indoor", ["counter", "reception", "bathroom", "kitchen island"], [], ["island"]],
               "lake": ["outdoor", ["water", "river"]],
               "lamp": ["indoor", ["chandelier", "pendant", "pendent", "candle", "bulb", "light"]],
               "land;ground;soil": ["outdoor", ["dirt", "earth"]],
               "light;light;source": ["indoor", ["candle", "bulb", "light", "lamp", "chandelier",
                                                 "pendant", "pendent", "candle", "bulb"], [], ["source"]],
               "microwave;microwave;oven": ["indoor", []],
               "minibike;motorbike": ["", ["bike", "motorcycle"]],
               "mirror": ["indoor", ["reflection"]],
               "monitor;monitoring;device": ["indoor", ["screen", "tv", "television", "laptop", "tablet", "computer"],
                                             [], ["device"]],
               "mountain;mount": ["outdoor", ["hill"]],
               "ottoman;pouf;pouffe;puff;hassock": ["indoor", ["chair", "seat", "couch",
                                                               "sofa", "lounge", "armchair"]],
               "oven": ["indoor", []],
               "painting;picture": ["indoor", ["drawing", "frame", "art", "advertisement", "sign", "notice board",
                                               "poster", "placard", "billboard"]],
               "palm;palm;tree": ["", ["coconut tree", "palm tree"], [], ["tree"]],
               "path": ["outdoor", ["dirt track", "field road", "dirt road", "path", "pathway"]],
               "person;individual;someone;somebody;mortal;soul": ["", ["girl", "guy", "man", "woman",
                                                                       "boy", "friend", "people",
                                                                       "family", "colleague", "child",
                                                                       "children", "crowded",
                                                                       "crowds", "lines", "queue"]],
               "pier;wharf;wharfage;dock": ["outdoor", []],
               "pillow": ["indoor", ["cushion"]],
               "plant;flora;plant;life": ["", ["potted plant", "flower", "leaf", "tree", "garden", "grass"
                                                                                                   "greenhouse"], [],
                                          ["life"]],
               "plate": ["indoor", []],
               "plaything;toy": ["", ["doll", "miniature", "teddy bear"]],
               "pole": ["", ["column", "pillar"]],
               "pool;table;billiard;table;snooker;table": ["indoor", ["pool table", "billiard table", "snooker table"],
                                                           [],
                                                           ["table"]],
               "poster;posting;placard;notice;bill;card": ["", ["picture", "frame", "sign", "painting",
                                                                "bulletin board", "sign board",
                                                                "advertisement", "sign", "notice board", "billboard"]],
               "pot;flowerpot": ["", ["vase", "potted plant", "flower pot", "plant pot"]],
               "radiator": ["indoor", []],
               "railing;rail": ["", ["fence", "fencing", "bannister", "banister", "balustrade", "balusters", "handrail",
                                     "balcony"]],
               "refrigerator;icebox": ["", ["fridge"]],
               "river": ["", []],
               "road;route": ["outdoor", ["crosswalk", "street"]],
               "rock;stone": ["outdoor", ["canyon", "creek"]],
               "rug;carpet;carpeting": ["indoor", ["floor", "flooring"]],
               "runway": ["outdoor", []],
               "sand": ["outdoor", ["beach", "seaside", "desert"]],
               "sconce": ["indoor", ["lamp", "candle", "bulb", "light", "chandelier",
                                     "pendant", "pendent", "candle", "bulb", "light"]],
               "screen;door;screen": ["", ["screen door", "glass door"], [], ["screen"]],
               "screen;silver;screen;projection;screen": ["indoor", ["projection screen", "conference", "lecture"],
                                                          [], ["silver"]],
               "sculpture": ["", ["miniature", "toy", "pedestal"]],
               "sea": ["outdoor", ["ocean", "beach", "coast"]],
               "seat": ["indoor", ["couch", "sofa", "lounge", "armchair",
                                   "chair", "airplane cabin", "auditorium",
                                   "conference center", "stool"]],
               "shelf": ["indoor", ["bookcase", "bookshelf"]],
               "ship": ["outdoor", ["boat"]],
               "shower": ["indoor", ["bathroom"]],
               "sidewalk;pavement": ["outdoor", []],
               "signboard;sign": ["", ["poster",
                                       "sign board", "advertisement", "picture", "frame", "sign", "painting",
                                       "bulletin board", "sign", "notice board", "billboard"]],
               "sink": ["indoor", ["bathroom", "kitchen"]],
               "sky": ["outdoor", ["cloudy", "cloud", "outside"]],
               "skyscraper": ["outdoor", ["building", "tower"]],
               "sofa;couch;lounge": ["indoor", ["armchair", "seat", "ottoman", "chair"]],
               "stage": ["indoor", []],
               "stairs;steps": ["", ["stairway", "staircase"]],
               "stairway;staircase": ["", ["stairs", "step"]],
               "step;stair": ["", ["stairs", "step", "stairway", "staircase"]],
               "stool": ["indoor", ["couch", "sofa", "lounge", "armchair",
                                    "chair", "airplane cabin", "auditorium",
                                    "conference center"]],
               "stove;kitchen;stove;range;kitchen;range;cooking;stove": ["indoor", [], [], ["range"]],
               "streetlight;street;lamp": ["outdoor", ["street lamp", "street light", "pole"]],
               "swimming;pool;swimming;bath;natatorium": ["", []],
               "swivel;chair": ["indoor", ["couch", "sofa", "lounge", "armchair",
                                           "chair", "airplane cabin", "auditorium",
                                           "conference center"]],
               "table": ["indoor", ["dining table"]],
               "tank;storage;tank": ["", [], [], ["storage"]],
               "television;television;receiver;television;set;tv;tv;set;idiot;box;boob;tube;telly;goggle;box": ["", [],
                                                                                                                [], [
                                                                                                                    "receiver",
                                                                                                                    "set",
                                                                                                                    "box",
                                                                                                                    "idiot",
                                                                                                                    "boob",
                                                                                                                    "tube"]],
               "tent;collapsible;shelter": ["", []],
               "toilet;can;commode;crapper;pot;potty;stool;throne": ["", ["bathroom", "restroom"], [],
                                                                     ["can", "pot", "throne"]],
               "towel": ["indoor", []],
               "tower": ["outdoor", ["building"]],
               "trade;name;brand;name;brand;marque": ["", [], [], ["brand", "trade"]],
               "traffic;light;traffic;signal;stoplight": ["outdoor", ["traffic light"], [], ["traffic", "signal"]],
               "tray": ["indoor", []],
               "tree": ["outdoor", ["forest", "jungle", "greenery", "plant", "garden", "lawn"]],
               "truck;motortruck": ["outdoor", ["van"]],
               "van": ["outdoor", ["truck"]],
               "vase": ["indoor", ["flowerpot", "flower"]],
               "wardrobe;closet;press": ["indoor", ["cabinet", "clothes"]],
               "washer;automatic;washer;washing;machine": ["indoor", ["washing machine"], [], ["automatic"]],
               "water": ["", ["lake", "pool", "ocean", "sea", "river", "flood", "beach"]],
               "waterfall;falls": ["outdoor", ["fall"]],
               "windowpane;window": ["", ["window pane"]],
               "wall": ["", []],
               "train": ["", []],
               "fire hydrant": ["", []],
               "stop sign": ["", []],
               "parking meter": ["", []],
               "umbrella": ["", []],
               "frisbee": ["", []],
               "skis": ["", []],
               "snowboard": ["", []],
               "kite": ["", []],
               "baseball bat": ["", []],
               "baseball glove": ["", []],
               "skateboard": ["", []],
               "surfboard": ["", []],
               "tennis racket": ["", []],
               "cup": ["", []],
               "fork": ["", []],
               "knife": ["", []],
               "spoon": ["", []],
               "bowl": ["", []],
               "remote": ["", []],
               "cell phone": ["", []],
               "toaster": ["", []],
               "scissors": ["", []],
               "hair drier": ["", []],
               "toothbrush": ["", []],
               "keyboard": ["", []],
               }
for word in map2deeplab:
    map2deeplab[word] = add_itself(word, map2deeplab[word])

# Final keywords
simples = {"none": ['none'],
           "wall": ["wall"],
           "fence": ["fence;fencing"],
           "sky": ["sky"],
           "tree": ["tree", "plant;flora;plant;life", "palm;palm;tree"],
           "path": ["road;route", "sidewalk;pavement", "path", "dirt;track"],
           "bed": ["bed", "blanket;cover"],
           "cradle": ["cradle"],
           "toy": ["plaything;toy"],
           "clock": ["clock"],
           "earth": ["grass", "field", "land;ground;soil", "earth;ground", "sand"],
           "mountain": ["mountain;mount", "hill", "rock;stone"],
           "table": ["table", "pool;table;billiard;table;snooker;table", "coffee;table;cocktail;table"],
           "seat": ["chair", "seat", "swivel;chair", "stool"],
           "sofa": ["sofa;couch;lounge", "armchair", "bench",
                    "ottoman;pouf;pouffe;puff;hassock"],
           "water": ["water", "sea", "river", "waterfall;falls", "lake"],
           "closet": ["wardrobe;closet;press", "chest;of;drawers;chest;bureau;dresser"],
           "clothes": ["apparel;wearing;apparel;dress;clothes"],
           "lamp": ["lamp", "chandelier;pendant;pendent", "sconce"],
           "pole": ["column;pillar", "pole"],
           "bathroom": ["bathtub;bathing;tub;bath;tub", "toilet;can;commode;crapper;pot;potty;stool;throne", "shower"],
           "sink": ["sink", "fountain", "tank;storage;tank"],
           "towel": ["towel"],
           "picture": ["signboard;sign", "poster;posting;placard;notice;bill;card",
                       "trade;name;brand;name;brand;marque",
                       "bulletin;board;notice;board", "painting;picture"],
           "flag": ["flag"],
           "building": ["building;edifice", "skyscraper", "tower", "house", "hovel;hut;hutch;shack;shanty"],
           "runway": ["runway"],
           "plane": ["airplane;aeroplane;plane"], "stage": ["stage"],
           "conveyer belt": ["conveyer;belt;conveyor;belt;conveyer;conveyor;transporter"],
           "cushion": ["cushion", "pillow"],
           "bag": ["bag"],
           "floor": ["floor;flooring", "rug;carpet;carpeting"],
           "rail": ["railing;rail", "bannister;banister;balustrade;balusters;handrail"],
           "stairs": ["grandstand;covered;stand", "stairs;steps", "stairway;staircase",
                      "escalator;moving;staircase;moving;stairway",
                      "step;stair"],
           "cabinet": ["cabinet", "shelf", "bookcase", "case;display;case;showcase;vitrine"],
           "book": ["book"],
           "counter": ["desk", "counter", "countertop", "bar", "kitchen;island"],
           "door": ["door;double;door"],
           "fireplace": ["fireplace;hearth;open;fireplace"],
           "fridge": ["refrigerator;icebox"],
           "stove": ["stove;kitchen;stove;range;kitchen;range;cooking;stove", "oven", "microwave;microwave;oven",
                     "toaster"],
           "radiatior": ["radiator"],
           "arcade machine": ["arcade;machine"],
           "car": ["car;auto;automobile;machine;motorcar"],
           "bus": ["bus;autobus;coach;charabanc;double-decker;jitney;motorbus;motorcoach;omnibus;passenger;vehicle"],
           "truck": ["truck;motortruck", "van"],
           "light": ["light;light;source"],
           "streetlight": ["streetlight;street;lamp", "traffic;light;traffic;signal;stoplight"],
           "buffet": ["buffet;counter;sideboard"],
           "food": ["food;solid;food"],
           "boat": ["boat", "ship"],
           "barrel": ["barrel;cask"],
           "ceiling": ["ceiling"],
           "curtain": ["curtain;drape;drapery;mantle;pall"],
           "sunshade": ["awning;sunshade;sunblind", "canopy"],
           "tent": ["tent;collapsible;shelter"],
           "exhaust hood": ["hood;exhaust;hood"],
           "swimming pool": ["swimming;pool;swimming;bath;natatorium"],
           "box": ["box", "basket;handbasket"],
           "ball": ["ball"],
           "person": ["person;individual;someone;somebody;mortal;soul"],
           "animal": ["animal;animate;being;beast;brute;creature;fauna"],
           "bike": ["minibike;motorbike", "bicycle;bike;wheel;cycle"],
           "washer": ["washer;automatic;washer;washing;machine", "dishwasher;dish;washer;dishwashing;machine"],
           "fan": ["fan"],
           "mirror": ["mirror", "screen;door;screen", "blind;screen"],
           "screen": ["crt;screen",
                      "computer;computing;machine;computing;device;data;processor;electronic;computer;information;processing;system",
                      "screen;silver;screen;projection;screen", "monitor;monitoring;device"],
           "booth": ["booth;cubicle;stall;kiosk"],
           "tv": ["television;television;receiver;television;set;tv;tv;set;idiot;box;boob;tube;telly;goggle;box"],
           "flower": ["flower", "pot;flowerpot", "vase"],
           "sculpture": ["sculpture", "base;pedestal;stand"],
           "trashbin": ["ashcan;trash;can;garbage;can;wastebin;ash;bin;ash-bin;ashbin;dustbin;trash;barrel;trash;bin"],
           "bridge": ["bridge;span", "pier;wharf;wharfage;dock"],
           "tray": ["tray", "plate"],
           "window": ["windowpane;window"],
           "bottle": ["bottle"],
           "drinking glass": ["glass;drinking;glass", "cup"],
           "train": ["train"],
           "fire hydrant": ["fire hydrant"],
           "stop sign": ["stop sign"],
           "parking meter": ["parking meter"],
           "umbrella": ["umbrella"],
           "frisbee": ["frisbee"],
           "skis": ["skis"],
           "snowboard": ["snowboard"],
           "kite": ["kite"],
           "keyboard": ["keyboard"],
           "baseball bat": ["baseball bat"],
           "baseball glove": ["baseball glove"],
           "skateboard": ["skateboard"],
           "surfboard": ["surfboard"],
           "tennis racket": ["tennis racket"],
           "fork": ["fork"],
           "knife": ["knife"],
           "spoon": ["spoon"],
           "bowl": ["bowl"],
           "remote": ["remote"],
           "cell phone": ["cell phone"],
           "toaster": ["toaster"],
           "scissors": ["scissors"],
           "hair drier": ["hair drier"],
           "toothbrush": ["toothbrush"]
           }
deeplab2simple = {}
for index, (simple, keywords) in enumerate(simples.items()):
    for kw in keywords:
        deeplab2simple[kw] = simple

json.dump(map2deeplab, open(f"{COMMON_PATH}/map2deeplab.json", 'w'))
json.dump(deeplab2simple, open(f"{COMMON_PATH}/deeplab2simple.json", "w"))
json.dump(simples, open(f"{COMMON_PATH}/simples.json", 'w'))
